import type { Metadata } from "next";
import {  Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";


const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ['500','600','700','800'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", outfit.className, "font-sans")}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
